Follow System Pagination added
bounswe/bounswe2020group7 pull request #241
Opened 2020-12-11 10:41 UTC by cakmadam98

Unit tests are passed since it is backwards compatible. Also I've corrected a small typo in the FollowRequest documentation.

2020-12-11 15:54 UTC, HUmutOzdemir requested changes

2020-12-11 15:54 UTC, HUmutOzdemir commented on Platon/backend/app/follow_system/forms.py
> +get_followings_parser.add_argument('per_page',type=int,help="Number of items in a page",location='form')
Why did you took this parameters form the body? As I know there is no body content in GET/HEAD requests.

2020-12-11 15:54 UTC, HUmutOzdemir commented on Platon/backend/app/follow_system/forms.py
> +get_followers_parser.add_argument('per_page',type=int,help="Number of items in a page",location='form')
Same as above

2020-12-11 15:54 UTC, HUmutOzdemir commented on Platon/backend/app/follow_system/forms.py
> +get_follow_requests_parser.add_argument('per_page',type=int,help="Number of items in a page",location='form')
Same as above

2020-12-11 20:07 UTC, HUmutOzdemir approved these changes
After the last changes that you did. I think we can merge your code.

2020-12-14 11:11 UTC, hilal-demir approved these changes

2020-12-14 20:28 UTC, merged